### ISSUE TITLE
a mistake about 'autoescape' on the website doc.

### ISSUE THREAD

**Issue by xesam** [Pinjasaur/templater.js#6]
the api sample about `autoescape` on [https://pinjasaur.github.io/templater.js/](https://pinjasaur.github.io/templater.js/) :

```
const tmpl = "Hi, I'm {{name}}"
const data = { name: "<Paul>" }
templater(tmpl, { autoescape: false })(data) // Hi, I'm <Paul>
```

it should be :

```
const tmpl = "Hi, I'm {{name}}"
const data = { name: "<Paul>" }
templater(tmpl)(data, { autoescape: false }) // Hi, I'm <Paul>
```

![1](https://github.com/user-attachments/assets/957641f4-67e2-4aa8-8fef-c31237b232e9)

**Comment by Pinjasaur** [comment]
Thanks @xesam, good catch.
